// Renders one WPT reftest (plus references) per testable case, and the manifest that
// records what the reference expects for EVERY case, testable or not.
//
// Reftest semantics (web-platform-tests docs, "Multiple References"): with several links
// the test passes if at least one `match` reference matches AND every `mismatch`
// reference differs. So an allowed set of real outcomes becomes several match refs,
// and "anything but these" becomes mismatch refs.
//
// References never depend on the descriptor or the matching under test: each is a
// plain face with the axis PINNED through font-variation-settings, which 7.2 says wins.

import { cells } from "./cases.mjs";

const FONT_FAMILY = "matrix test font";

const esc = (s) => s.replaceAll("&", "&amp;").replaceAll("<", "&lt;");
const token = (o) => (o.kind === "upright" ? "upright" : `slnt${o.value}`);
const pinned = (o) => `font-variation-settings: 'slnt' ${o.kind === "upright" ? 0 : o.value};`;
const describe = (o) =>
  o.kind === "upright" ? "upright" : o.kind === "synth" ? `a synthesized ${o.angle}deg skew` : `${o.axis} ${o.value}`;

function faceRule(matrix, descriptor) {
  const line = descriptor ? `\n    font-style: ${descriptor};` : "";
  return `  @font-face {
    font-family: "${FONT_FAMILY}";
    src: url('${matrix.font.file}');${line}
  }`;
}

const SCRIPT = `<script>
  document.fonts.ready.then(() => {
    document.documentElement.classList.remove('reftest-wait');
  });
</script>`;

function paragraph(cell, matrix) {
  const g = matrix.font.glyph;
  if (cell.row.em) {
    const style = cell.css ? ` style="${cell.css}"` : "";
    return `<p class="test"${style}><em>${g}</em></p>`;
  }
  return `<p class="test" style="${cell.css}">${g}</p>`;
}

function refHtml(cell, matrix, outcome, kind) {
  const what = kind === "match" ? "must render like" : "must NOT render like";
  return `<!DOCTYPE html>
<html lang="en" class="reftest-wait">
<meta charset="utf-8" />
<title>Reference for ${cell.address} (${cell.id}): ${describe(outcome)}</title>
<!--
  Reference for ${cell.address}: ${describe(outcome)}. The test ${what} this. A plain face
  with the axis pinned through font-variation-settings (which wins over any style-derived
  variation, CSS Fonts 4 7.2), so this reference does not depend on the descriptor or on the
  matching under test.
-->
<link rel="stylesheet" href="../oblique-matching.css">
<style>
${faceRule(matrix, null)}
  .test {
    font-family: "${FONT_FAMILY}";
    font-size: ${matrix.font.fontSize};
    ${pinned(outcome)}
  }
</style>
${SCRIPT}

<p class="test">${matrix.font.glyph}</p>
`;
}

function testHtml(cell, matrix, refs) {
  const e = cell.expected;
  const allowed = e.allowed.map(describe).join("; ");
  const links = [
    `<link rel="help" href="https://drafts.csswg.org/css-fonts-4/#font-style-matching" />`,
    `<link rel="help" href="https://drafts.csswg.org/css-fonts-4/#font-synthesis-style" />`,
    ...refs.map((r) => `<link rel="${r.kind}" href="${r.file}">`),
  ].join("\n");
  const rule = [
    e.plan.match.length ? `must render like one of: ${e.plan.match.map(describe).join(", ")}` : "",
    e.plan.mismatch.length ? `must NOT render like any of: ${e.plan.mismatch.map(describe).join(", ")}` : "",
  ].filter(Boolean).join("; ");
  const desc = cell.col.descriptor ? `font-style: ${cell.col.descriptor}` : "no font-style descriptor (auto)";
  return `<!DOCTYPE html>
<html lang="en" class="reftest-wait">
<meta charset="utf-8" />
<title>CSS Test: ${esc(cell.address)} ${esc(desc)} + ${esc(cell.row.lines.join(" "))}</title>
<!--
  GENERATED by reference/src/cli.mjs from reference/cases/matrix.json: do not edit.
  Cell ${cell.address}: @font-face ${desc}, request "${cell.row.request}"${cell.row.em ? " (through <em>)" : ""}${cell.row.fvs ? " (through font-variation-settings)" : ""}.
  Status: ${e.status}. The reference algorithm permits: ${allowed}.
  ${e.why.join("\n  ")}${e.assumptions.length ? "\n  Assumptions: " + e.assumptions.join("; ") : ""}
  font-synthesis is left at its default: a matched request must not be synthesized.
-->
${links}
<meta name="assert"
  content="A face ${cell.col.descriptor ? `declared '${esc(desc)}'` : "with no font-style descriptor (auto)"}, requested with '${esc(cell.row.lines.join(" "))}', ${esc(rule)}." />
<link rel="stylesheet" href="../oblique-matching.css">
<!-- Font: ${matrix.font.file}: ${matrix.font.note} -->
<style>
${faceRule(matrix, cell.col.descriptor)}
  .test {
    font-family: "${FONT_FAMILY}";
    font-size: ${matrix.font.fontSize};
  }
</style>
${SCRIPT}

${paragraph(cell, matrix)}
`;
}

/** @returns {{files: Map<string,string>, manifest: object}} */
export function generate(matrix) {
  const files = new Map();
  const manifestCells = [];
  for (const cell of cells(matrix)) {
    const e = cell.expected;
    const refs = [
      ...e.plan.match.map((o) => ({ kind: "match", outcome: o, file: `${cell.id}-${token(o)}-ref.html` })),
      ...e.plan.mismatch.map((o) => ({ kind: "mismatch", outcome: o, file: `${cell.id}-${token(o)}-notref.html` })),
    ];
    const wpt = refs.length > 0;
    if (wpt) {
      files.set(`${cell.id}.html`, testHtml(cell, matrix, refs));
      for (const r of refs) files.set(r.file, refHtml(cell, matrix, r.outcome, r.kind));
    }
    manifestCells.push({
      address: cell.address,
      id: cell.id,
      row: cell.row.slug,
      column: cell.col.slug,
      request: cell.row.request,
      descriptor: cell.col.descriptor,
      css: cell.css,
      status: e.status,
      allowed: e.allowed,
      plan: e.plan,
      selected: e.selected,
      stage: e.stage,
      assumptions: e.assumptions,
      why: e.why,
      wpt,
      files: wpt ? [`${cell.id}.html`, ...refs.map((r) => r.file)] : [],
    });
  }
  const manifest = {
    _note: "GENERATED by reference/src/cli.mjs from reference/cases/matrix.json. Do not edit.",
    font: matrix.font,
    columns: matrix.columns,
    rows: matrix.rows,
    cells: manifestCells,
  };
  files.set("matrix.manifest.json", JSON.stringify(manifest, null, 2) + "\n");
  return { files, manifest };
}
