"""The site's coverage matrix: @font-face `font-style` descriptor (columns) x
use-site CSS (rows), one test per cell (5 x 6 = 30), all against one font
(tests/oblique-style-matching/resources/Cairo.var.subset.ttf).

Imported by generate-site-data.py. Everything here is data + rendering; the
per-engine results themselves come from results/browser-matrix.md (this
repo's own `wpt run` results), never from upstream wpt.fyi data.

Each cell holds exactly ONE test, generated by
tests/oblique-style-matching/resources/gen-matrix.py, whose grid this module
imports. A blank cell would mean "no test yet"; none are blank today.

verify_matrix() fails loudly, same discipline as verify_category_mapping():
every cell's test must exist, be recorded in browser-matrix.md, and its HTML
must actually contain the descriptor and use-site CSS the cell claims.
"""
import hashlib
import html
import importlib.util
import re
import shutil
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TESTS_DIR = REPO_ROOT / "tests" / "oblique-style-matching"
FONT_SRC = TESTS_DIR / "resources" / "Cairo.var.subset.ttf"
FONT_PUBLIC = REPO_ROOT / "site" / "public" / "Cairo.var.subset.ttf"
GENERATOR = TESTS_DIR / "resources" / "gen-matrix.py"
TEST_URL_BASE = "https://github.com/amitkaps/oblique/blob/main/tests/oblique-style-matching/"

# Column = what the @font-face declares. `css` is the descriptor line the
# tests use (None = no font-style descriptor at all, which is defined as
# `auto`). The id also names the live specimen's font-family ("ob-<id>").
COLUMNS = [
    {"id": "auto", "css": None, "code": "@font-face { /* font-style omitted */ }",
     "note": "Descriptor omitted, which is defined as auto: matched as if normal"},
    {"id": "normal", "css": "font-style: normal;", "code": "@font-face { font-style: normal; }",
     "note": "Declared upright"},
    {"id": "italic", "css": "font-style: italic;", "code": "@font-face { font-style: italic; }",
     "note": "Declared italic (binary, no angle)"},
    {"id": "oblique-bare", "css": "font-style: oblique;", "code": "@font-face { font-style: oblique; }",
     "note": "Declared oblique, no range"},
    {"id": "oblique-range", "css": "font-style: oblique -11deg 11deg;",
     "code": "@font-face { font-style: oblique -11deg 11deg; }",
     "note": "Declared oblique with the font's true slnt range"},
]

# Row = the use-site CSS. `lines` is what the header shows; `css` is the
# inline style the live specimen applies (None for <em>, which gets
# `font-style: italic` from the UA stylesheet). `check` = a regex the test's
# use-site paragraph must match. No row sets font-synthesis: the spec
# synthesizes only when a family lacks a suitable face, so a matched request
# must never synthesize, and forcing it off would hide a browser that does.
ROWS = [
    {"num": 1, "id": "normal", "lines": ["font-style: normal;"],
     "css": "font-style: normal;", "check": r"font-style: normal"},
    {"num": 2, "id": "italic", "lines": ["font-style: italic;"],
     "css": "font-style: italic;", "check": r"font-style: italic"},
    {"num": 3, "id": "oblique", "lines": ["font-style: oblique;"],
     "css": "font-style: oblique;", "check": r"font-style: oblique;"},
    {"num": 4, "id": "oblique-11deg", "lines": ["font-style: oblique 11deg;"],
     "css": "font-style: oblique 11deg;", "check": r"font-style: oblique 11deg"},
    {"num": 5, "id": "em", "lines": ["<em>"], "css": "", "em": True, "check": r"<em>"},
    {"num": 6, "id": "slnt", "lines": ["font-variation-settings: 'slnt' -11;"],
     "css": "font-variation-settings: 'slnt' -11;", "check": r"font-variation-settings: \"slnt\" -11"},
]

# The pink layer of each specimen: what the test's own reference renders.
REF_CSS = {
    "upright": "",
    "slnt-11": "font-variation-settings: 'slnt' -11;",
    "slnt-0": "font-variation-settings: 'slnt' 0;",
}


def _load_generator():
    """The cell table (which test sits where, and what it must render) lives
    in the test generator: one source of truth. Its filename has a hyphen, so
    it is loaded by path."""
    spec = importlib.util.spec_from_file_location("gen_matrix", GENERATOR)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


_GEN = _load_generator()

# (column id, row id) -> {"test": test id, "ref": expected-rendering kind}.
CELLS = {
    key: {"test": _GEN.slug(*key), "ref": kind}
    for key, (kind, _note) in _GEN.GRID.items()
}

ENGINES = [
    {"id": "chromium", "result_key": "chrome", "label": "Chromium"},
    {"id": "firefox", "result_key": "firefox", "label": "Firefox"},
    {"id": "safari", "result_key": "safari", "label": "Safari"},
]

SPECIMEN_WORD = "OBLIQUE"


def _norm(s: str) -> str:
    return re.sub(r"\s+", " ", s.replace("'", '"'))


def _face_block(text: str) -> str:
    """The @font-face rule inside the test's <style> (not one merely quoted in
    a title, comment or assert), with CSS comments stripped."""
    style = re.search(r"<style>(.*?)</style>", text, re.S)
    m = re.search(r"@font-face\s*\{(.*?)\}", style.group(1), re.S) if style else None
    return re.sub(r"/\*.*?\*/", "", m.group(1), flags=re.S) if m else ""


def verify_matrix(matrix_by_id: dict):
    """Fail loudly on any drift between this table and the tests on disk."""
    col_ids = {c["id"] for c in COLUMNS}
    row_ids = {r["id"] for r in ROWS}
    if set(_GEN.COLS) != col_ids or set(_GEN.ROWS) != row_ids:
        raise RuntimeError("coverage_matrix: columns/rows here disagree with resources/gen-matrix.py")
    if set(CELLS) != {(c, r) for c in col_ids for r in row_ids}:
        raise RuntimeError("coverage_matrix: the generator's grid is not exactly columns x rows")

    cols = {c["id"]: c for c in COLUMNS}
    rows = {r["id"]: r for r in ROWS}
    for (col, row), cell in CELLS.items():
        tid = cell["test"]
        path = TESTS_DIR / f"{tid}.html"
        if not path.exists():
            raise RuntimeError(f"coverage_matrix: cell {(col, row)!r} names {tid!r}, but "
                               f"{path.name} is missing: run resources/gen-matrix.py")
        refs = [f"{tid}-notupright-ref.html", f"{tid}-notaxis-ref.html"] \
            if cell["ref"] == "MISMATCH-notsynth" else [f"{tid}-ref.html"]
        for r in refs:
            if not (TESTS_DIR / r).exists():
                raise RuntimeError(f"coverage_matrix: {r} is missing for {tid!r}")
        if tid not in matrix_by_id:
            raise RuntimeError(f"coverage_matrix: {tid!r} has no row in results/browser-matrix.md "
                               f"-- run and record it first")
        raw = path.read_text()
        text = _norm(raw)
        if FONT_SRC.name not in text:
            raise RuntimeError(f"coverage_matrix: {tid!r} does not use {FONT_SRC.name}")
        if "font-synthesis" in text.replace("font-synthesis is deliberately", "").replace("font-synthesis-style", ""):
            raise RuntimeError(f"coverage_matrix: {tid!r} sets font-synthesis; the matrix runs at the default")
        face = _norm(_face_block(raw))
        desc = cols[col]["css"]
        if desc is None:
            if "font-style" in face:
                raise RuntimeError(f"coverage_matrix: {tid!r} is in the auto column but its "
                                   f"@font-face declares a font-style")
        elif _norm(desc) not in face:
            raise RuntimeError(f"coverage_matrix: {tid!r} is in the {col!r} column but its "
                               f"@font-face does not contain {desc!r}")
        m = re.search(r'<p class="test"[^\n]*', raw)
        if not m or not re.search(_norm(rows[row]["check"]), _norm(m.group(0))):
            raise RuntimeError(f"coverage_matrix: {tid!r} is in row {row!r} but its use-site "
                               f"paragraph does not match {rows[row]['check']!r}")

    on_disk = {p.name[:-5] for p in TESTS_DIR.glob("matrix-*.html")
               if not p.name.endswith("-ref.html")}
    expected = {c["test"] for c in CELLS.values()}
    if on_disk != expected:
        raise RuntimeError(f"coverage_matrix: matrix-* tests on disk disagree with the grid: "
                           f"extra {sorted(on_disk - expected)}, missing {sorted(expected - on_disk)}")


def sync_font(strict_check=True):
    """Copy the test font to site/public/ so the page's live specimens use
    the exact file the tests do. Copied, not symlinked (Vite/deploy copy)."""
    FONT_PUBLIC.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(FONT_SRC, FONT_PUBLIC)
    a = hashlib.sha256(FONT_SRC.read_bytes()).hexdigest()
    b = hashlib.sha256(FONT_PUBLIC.read_bytes()).hexdigest()
    if strict_check and a != b:
        raise RuntimeError("coverage_matrix: site font copy differs from the test font")


def build_cell_results(matrix_by_id, status_fn):
    """{(col,row): {'chrome': status, 'firefox': ..., 'safari': ...}}"""
    out = {}
    for key, cell in CELLS.items():
        out[key] = {e["result_key"]: status_fn(cell["test"], matrix_by_id, e["result_key"])
                    for e in ENGINES}
    return out


def cell_status(results: dict) -> str:
    """Border colour: only engines that were actually run count, so a cell
    isn't marked uncertain just because Safari has no stable run yet."""
    vals = {v for v in results.values() if v in ("pass", "fail")}
    if "fail" in vals:
        return "fail"
    if vals == {"pass"}:
        return "pass"
    return "unknown"


def _summary(cell_results):
    covered = len(CELLS)
    total = len(COLUMNS) * len(ROWS)
    diverge = [k for k, r in cell_results.items()
               if r["chrome"] != r["firefox"] and {r["chrome"], r["firefox"]} <= {"pass", "fail"}]
    return covered, total, diverge, len({CELLS[k]["test"] for k in diverge})


def font_face_css() -> str:
    """One @font-face per column, all the same file: the live specimens."""
    out = []
    for c in COLUMNS:
        line = f"  font-style: {c['css'].split(': ', 1)[1]}" if c["css"] else ""
        out.append(f'@font-face {{ font-family: "ob-{c["id"]}"; src: url("/Cairo.var.subset.ttf");{line} }}')
    return "\n".join(out)


def _specimen(col, row, cell) -> str:
    e = html.escape
    css = row["css"]
    is_em = row.get("em", False)
    family = f"font-family: 'ob-{col['id']}';"
    word = e(SPECIMEN_WORD)
    inner = f"<em>{word}</em>" if is_em else word
    test = f'<span class="ov-test" style="{e(family + " " + css)}">{inner}</span>'
    if cell["ref"].startswith("MISMATCH"):
        return f'<div class="overlap overlap-single">{test}</div>'
    ref_style = family + " " + REF_CSS[cell["ref"]]
    ref = f'<span class="ov-control" style="{e(ref_style)}">{word}</span>'
    return f'<div class="overlap">{ref}{test}</div>'


def _badges(results: dict) -> str:
    e = html.escape
    lis = []
    for eng in ENGINES:
        status = results[eng["result_key"]]
        cls = {"pass": "pass", "fail": "fail"}.get(status, "unknown")
        word = {"pass": "pass", "fail": "fail"}.get(status, "not run")
        lis.append(
            f'<li class="b-badge {cls}" title="{e(eng["label"])}: {word}">'
            f'<img class="logo" src="/browsers/{eng["id"]}.svg" alt="{e(eng["label"])}"></li>'
        )
    return f'<ul class="verdicts">{"".join(lis)}</ul>'


def render_matrix_html(cell_results: dict, versions: dict) -> str:
    e = html.escape
    covered, total, diverge, diverge_tests = _summary(cell_results)
    parts = []

    div_txt = ""
    if diverge:
        div_txt = (f" &middot; <strong>{len(diverge)} cell{'s' if len(diverge) != 1 else ''} "
                   f"where Chrome and Firefox disagree</strong>")
    parts.append(f'<p class="matrix-count">{covered} of {total} cells have a test{div_txt}</p>')

    parts.append(
        '<pre class="face-block"><code>'
        "@font-face {\n"
        '  font-family: "Oblique Test";\n'
        "  src: url(Cairo.var.subset.ttf);  /* real Cairo, slnt -11..11, wght 200..1000 */\n"
        "  font-style: <em>&lt;column&gt;</em>;\n"
        "}"
        "</code></pre>"
    )

    parts.append('<div class="matrix-wrap"><table class="matrix"><thead><tr><th></th>')
    for c in COLUMNS:
        parts.append(f'<th><code>{e(c["code"])}</code><span class="col-note">{e(c["note"])}</span></th>')
    parts.append("</tr></thead><tbody>")

    for row in ROWS:
        lines = "<br>".join(e(l) for l in row["lines"])
        parts.append(f'<tr><th scope="row"><span class="row-num">{row["num"]}.</span> <code>{lines}</code></th>')
        for col in COLUMNS:
            key = (col["id"], row["id"])
            cell = CELLS.get(key)
            if cell is None:
                parts.append('<td class="status-blank"><span class="blank-cell">&mdash;</span>'
                             '<span class="cell-tags">no test yet</span></td>')
                continue
            res = cell_results[key]
            url = TEST_URL_BASE + cell["test"] + ".html"
            tags = ""
            if cell["ref"] == "MISMATCH-notsynth":
                tags += '<span class="tag">synthesized: not upright, not the axis</span>'
            elif cell["ref"] == "MISMATCH-upright":
                tags += '<span class="tag">synthesized: not upright</span>'
            parts.append(
                f'<td class="status-{cell_status(res)}">'
                f'<a class="specimen-link" href="{e(url)}" title="{e(cell["test"])}">'
                f'{_specimen(col, row, cell)}</a>'
                f'{_badges(res)}'
                f'<div class="cell-tags">{tags}</div></td>'
            )
        parts.append("</tr>")
    parts.append("</tbody></table></div>")

    parts.append(
        '<ul class="legend">'
        '<li><span class="b-badge pass"></span> pass</li>'
        '<li><span class="b-badge fail"></span> fail</li>'
        '<li><span class="b-badge unknown"></span> not run</li>'
        '<li class="legend-note">Hover a circle for the engine. Click a specimen for its test file.</li>'
        "</ul>"
    )
    ver = []
    for eng in ENGINES:
        v = versions.get(eng["result_key"])
        ver.append(f'<li><img class="logo" src="/browsers/{eng["id"]}.svg" alt="">'
                   f'{e(eng["label"])} {e(v) if v else "&mdash; not run"}</li>')
    parts.append(f'<ul class="legend legend-versions">{"".join(ver)}</ul>')
    return "".join(parts)
